server:
  port: 9527

spring:  application:     name: microservicecloud-zuul-gateway


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com 
    prefer-ip-address: true        

zuul:
#  prefix: /aistone
#  ignored-services: "*"
  routes:
    serviceId: microservicescloud-dept
    path: /mydept/**

info:
  app.name: aistone-springcloud
  company.name: www.aistone.com
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$